
name: Backend CD (live-pulse-talk)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - uses: actions/checkout@v2
    - name: Deploy to Render
      run: live-pulse-talk
        


